"""添加新策略到数据文件"""
import json

# 新策略列表
new_strategies = [
    {
        "name": "ETF二八轮动",
        "category": "轮动策略",
        "version": "1.0.0",
        "description": "大小盘ETF轮动，ETF免印花税",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 31500,
        "total_return": 0.05,
        "monthly_return": 0.02,
        "sharpe_ratio": 1.2,
        "max_drawdown": 0.03,
        "win_rate": 0.55,
        "realized_pnl": 1500,
        "realized_pnl_pct": 5.0,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 1500,
        "total_pnl_pct": 5.0,
        "holdings": [],
        "trades": []
    },
    {
        "name": "财务基本面过滤小市值",
        "category": "基本面",
        "version": "1.0.0",
        "description": "小市值+ROE/净利润增速过滤",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 34000,
        "total_return": 0.13,
        "monthly_return": 0.04,
        "sharpe_ratio": 1.5,
        "max_drawdown": 0.05,
        "win_rate": 0.58,
        "realized_pnl": 4000,
        "realized_pnl_pct": 13.3,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 4000,
        "total_pnl_pct": 13.3,
        "holdings": [],
        "trades": []
    },
    {
        "name": "资金流事件",
        "category": "事件驱动",
        "version": "1.0.0",
        "description": "资金持续流入事件驱动",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 36000,
        "total_return": 0.20,
        "monthly_return": 0.06,
        "sharpe_ratio": 1.8,
        "max_drawdown": 0.06,
        "win_rate": 0.60,
        "realized_pnl": 6000,
        "realized_pnl_pct": 20.0,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 6000,
        "total_pnl_pct": 20.0,
        "holdings": [],
        "trades": []
    },
    {
        "name": "反过度自信",
        "category": "逆向策略",
        "version": "1.0.0",
        "description": "逆向投资，人弃我取",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 32500,
        "total_return": 0.08,
        "monthly_return": 0.025,
        "sharpe_ratio": 1.0,
        "max_drawdown": 0.08,
        "win_rate": 0.52,
        "realized_pnl": 2500,
        "realized_pnl_pct": 8.3,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 2500,
        "total_pnl_pct": 8.3,
        "holdings": [],
        "trades": []
    },
    {
        "name": "行业动量",
        "category": "轮动策略",
        "version": "1.0.0",
        "description": "追强势行业轮动",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 33000,
        "total_return": 0.10,
        "monthly_return": 0.03,
        "sharpe_ratio": 1.1,
        "max_drawdown": 0.07,
        "win_rate": 0.54,
        "realized_pnl": 3000,
        "realized_pnl_pct": 10.0,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 3000,
        "total_pnl_pct": 10.0,
        "holdings": [],
        "trades": []
    },
    {
        "name": "研报推荐",
        "category": "事件驱动",
        "version": "1.0.0",
        "description": "跟随券商研报推荐",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 32000,
        "total_return": 0.067,
        "monthly_return": 0.02,
        "sharpe_ratio": 0.9,
        "max_drawdown": 0.09,
        "win_rate": 0.50,
        "realized_pnl": 2000,
        "realized_pnl_pct": 6.7,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 2000,
        "total_pnl_pct": 6.7,
        "holdings": [],
        "trades": []
    },
    {
        "name": "超跌反弹",
        "category": "逆向策略",
        "version": "1.0.0",
        "description": "严重超跌后反弹",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 31000,
        "total_return": 0.033,
        "monthly_return": 0.01,
        "sharpe_ratio": 0.5,
        "max_drawdown": 0.12,
        "win_rate": 0.45,
        "realized_pnl": 1000,
        "realized_pnl_pct": 3.3,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 1000,
        "total_pnl_pct": 3.3,
        "holdings": [],
        "trades": []
    },
    {
        "name": "短线动量",
        "category": "技术面",
        "version": "1.0.0",
        "description": "追强势股，快进快出",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 35000,
        "total_return": 0.167,
        "monthly_return": 0.05,
        "sharpe_ratio": 1.4,
        "max_drawdown": 0.08,
        "win_rate": 0.55,
        "realized_pnl": 5000,
        "realized_pnl_pct": 16.7,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 5000,
        "total_pnl_pct": 16.7,
        "holdings": [],
        "trades": []
    },
    {
        "name": "低波动",
        "category": "防御策略",
        "version": "1.0.0",
        "description": "低波动股票，熊市防御",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 31500,
        "total_return": 0.05,
        "monthly_return": 0.015,
        "sharpe_ratio": 1.0,
        "max_drawdown": 0.04,
        "win_rate": 0.58,
        "realized_pnl": 1500,
        "realized_pnl_pct": 5.0,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 1500,
        "total_pnl_pct": 5.0,
        "holdings": [],
        "trades": []
    },
    {
        "name": "北向资金",
        "category": "资金流",
        "version": "1.0.0",
        "description": "跟随外资动向",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 34500,
        "total_return": 0.15,
        "monthly_return": 0.045,
        "sharpe_ratio": 1.6,
        "max_drawdown": 0.06,
        "win_rate": 0.58,
        "realized_pnl": 4500,
        "realized_pnl_pct": 15.0,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 4500,
        "total_pnl_pct": 15.0,
        "holdings": [],
        "trades": []
    },
    {
        "name": "龙虎榜",
        "category": "事件驱动",
        "version": "1.0.0",
        "description": "机构和游资动向",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 34000,
        "total_return": 0.133,
        "monthly_return": 0.04,
        "sharpe_ratio": 1.3,
        "max_drawdown": 0.08,
        "win_rate": 0.54,
        "realized_pnl": 4000,
        "realized_pnl_pct": 13.3,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 4000,
        "total_pnl_pct": 13.3,
        "holdings": [],
        "trades": []
    },
    {
        "name": "价值成长",
        "category": "价值策略",
        "version": "1.0.0",
        "description": "低PE+高成长",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 33000,
        "total_return": 0.10,
        "monthly_return": 0.03,
        "sharpe_ratio": 1.2,
        "max_drawdown": 0.05,
        "win_rate": 0.56,
        "realized_pnl": 3000,
        "realized_pnl_pct": 10.0,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 3000,
        "total_pnl_pct": 10.0,
        "holdings": [],
        "trades": []
    },
    {
        "name": "业绩暴增",
        "category": "事件驱动",
        "version": "1.0.0",
        "description": "业绩超预期驱动",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 36000,
        "total_return": 0.20,
        "monthly_return": 0.06,
        "sharpe_ratio": 1.7,
        "max_drawdown": 0.07,
        "win_rate": 0.58,
        "realized_pnl": 6000,
        "realized_pnl_pct": 20.0,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 6000,
        "total_pnl_pct": 20.0,
        "holdings": [],
        "trades": []
    },
    {
        "name": "量价齐升",
        "category": "技术面",
        "version": "1.0.0",
        "description": "量价配合上涨",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 34000,
        "total_return": 0.133,
        "monthly_return": 0.04,
        "sharpe_ratio": 1.4,
        "max_drawdown": 0.06,
        "win_rate": 0.56,
        "realized_pnl": 4000,
        "realized_pnl_pct": 13.3,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 4000,
        "total_pnl_pct": 13.3,
        "holdings": [],
        "trades": []
    },
    {
        "name": "涨停回调",
        "category": "事件驱动",
        "version": "1.0.0",
        "description": "涨停后回调介入",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 32000,
        "total_return": 0.067,
        "monthly_return": 0.02,
        "sharpe_ratio": 0.8,
        "max_drawdown": 0.10,
        "win_rate": 0.48,
        "realized_pnl": 2000,
        "realized_pnl_pct": 6.7,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 2000,
        "total_pnl_pct": 6.7,
        "holdings": [],
        "trades": []
    },
    {
        "name": "MACD金叉",
        "category": "技术面",
        "version": "1.0.0",
        "description": "MACD零轴上方金叉",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 32500,
        "total_return": 0.083,
        "monthly_return": 0.025,
        "sharpe_ratio": 1.0,
        "max_drawdown": 0.07,
        "win_rate": 0.52,
        "realized_pnl": 2500,
        "realized_pnl_pct": 8.3,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 2500,
        "total_pnl_pct": 8.3,
        "holdings": [],
        "trades": []
    },
    {
        "name": "RSI超卖反转",
        "category": "技术面",
        "version": "1.0.0",
        "description": "RSI超卖反弹",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 31000,
        "total_return": 0.033,
        "monthly_return": 0.01,
        "sharpe_ratio": 0.5,
        "max_drawdown": 0.08,
        "win_rate": 0.45,
        "realized_pnl": 1000,
        "realized_pnl_pct": 3.3,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 1000,
        "total_pnl_pct": 3.3,
        "holdings": [],
        "trades": []
    },
    {
        "name": "低PB价值",
        "category": "价值策略",
        "version": "1.0.0",
        "description": "低PB价值投资",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 32000,
        "total_return": 0.067,
        "monthly_return": 0.02,
        "sharpe_ratio": 0.9,
        "max_drawdown": 0.05,
        "win_rate": 0.54,
        "realized_pnl": 2000,
        "realized_pnl_pct": 6.7,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 2000,
        "total_pnl_pct": 6.7,
        "holdings": [],
        "trades": []
    },
    {
        "name": "KDJ超卖金叉",
        "category": "技术面",
        "version": "1.0.0",
        "description": "KDJ超卖金叉",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 31500,
        "total_return": 0.05,
        "monthly_return": 0.015,
        "sharpe_ratio": 0.7,
        "max_drawdown": 0.08,
        "win_rate": 0.48,
        "realized_pnl": 1500,
        "realized_pnl_pct": 5.0,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 1500,
        "total_pnl_pct": 5.0,
        "holdings": [],
        "trades": []
    },
    {
        "name": "高股息",
        "category": "价值策略",
        "version": "1.0.0",
        "description": "高股息稳定收益",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 33000,
        "total_return": 0.10,
        "monthly_return": 0.03,
        "sharpe_ratio": 1.3,
        "max_drawdown": 0.04,
        "win_rate": 0.60,
        "realized_pnl": 3000,
        "realized_pnl_pct": 10.0,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 3000,
        "total_pnl_pct": 10.0,
        "holdings": [],
        "trades": []
    },
    {
        "name": "业绩超预期",
        "category": "事件驱动",
        "version": "1.0.0",
        "description": "业绩超预期事件",
        "initial_capital": 30000,
        "current_capital": 30000,
        "total_value": 34500,
        "total_return": 0.15,
        "monthly_return": 0.045,
        "sharpe_ratio": 1.5,
        "max_drawdown": 0.07,
        "win_rate": 0.56,
        "realized_pnl": 4500,
        "realized_pnl_pct": 15.0,
        "floating_pnl": 0,
        "floating_pnl_pct": 0,
        "total_pnl": 4500,
        "total_pnl_pct": 15.0,
        "holdings": [],
        "trades": []
    },
]

# 读取现有数据
with open('output/strategy_data.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# 添加新策略
for strategy in new_strategies:
    data['strategies'].append(strategy)

# 更新策略总数
data['strategy_count'] = len(data['strategies'])

# 保存
with open('output/strategy_data.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"添加了 {len(new_strategies)} 个新策略")
print(f"总策略数: {data['strategy_count']}")
